// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for logo documents
 */
interface LogoDocumentData {
  /**
   * logo field in *logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * logo document from Prismic
 *
 * - **API ID**: `logo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LogoDocumentData>, "logo", Lang>;

type PageDocumentDataSlicesSlice =
  | TripSlice
  | TripsSlice
  | TeamSlice
  | StatisticsSlice
  | TestimonialsSlice
  | TourTypesSlice
  | ContentPreviewSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = LogoDocument | PageDocument;

/**
 * Item in *ContentPreview → Default → Primary → tour*
 */
export interface ContentPreviewSliceDefaultPrimaryTourItem {
  /**
   * img field in *ContentPreview → Default → Primary → tour*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_preview.default.primary.tour[].img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>;

  /**
   * title field in *ContentPreview → Default → Primary → tour*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_preview.default.primary.tour[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * content field in *ContentPreview → Default → Primary → tour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_preview.default.primary.tour[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *ContentPreview → Default → Primary*
 */
export interface ContentPreviewSliceDefaultPrimary {
  /**
   * title field in *ContentPreview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_preview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * content field in *ContentPreview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_preview.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * tour field in *ContentPreview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_preview.default.primary.tour[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tour: prismic.GroupField<Simplify<ContentPreviewSliceDefaultPrimaryTourItem>>;
}

/**
 * Default variation for ContentPreview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentPreviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentPreviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentPreview*
 */
type ContentPreviewSliceVariation = ContentPreviewSliceDefault;

/**
 * ContentPreview Shared Slice
 *
 * - **API ID**: `content_preview`
 * - **Description**: ContentPreview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentPreviewSlice = prismic.SharedSlice<
  "content_preview",
  ContentPreviewSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * content field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;

  /**
   * heroImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → withoutButton → Primary*
 */
export interface HeroSliceWithoutButtonPrimary {
  /**
   * heading field in *Hero → withoutButton → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withoutButton.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * content field in *Hero → withoutButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withoutButton.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * heroImage field in *Hero → withoutButton → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withoutButton.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;
}

/**
 * withoutButton variation for Hero Slice
 *
 * - **API ID**: `withoutButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithoutButton = prismic.SharedSliceVariation<
  "withoutButton",
  Simplify<HeroSliceWithoutButtonPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithoutButton;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Statistics → Default → Primary → stats*
 */
export interface StatisticsSliceDefaultPrimaryStatsItem {
  /**
   * icon field in *Statistics → Default → Primary → stats*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.stats[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * number field in *Statistics → Default → Primary → stats*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  number: prismic.RichTextField;

  /**
   * stat_content field in *Statistics → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.stats[].stat_content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stat_content: prismic.KeyTextField;
}

/**
 * Primary content in *Statistics → Default → Primary*
 */
export interface StatisticsSliceDefaultPrimary {
  /**
   * title field in *Statistics → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * content field in *Statistics → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * stats field in *Statistics → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<StatisticsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisticsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatisticsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Statistics*
 */
type StatisticsSliceVariation = StatisticsSliceDefault;

/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: Statistics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisticsSlice = prismic.SharedSlice<
  "statistics",
  StatisticsSliceVariation
>;

/**
 * Item in *Team → Default → Primary → member*
 */
export interface TeamSliceDefaultPrimaryMemberItem {
  /**
   * profile field in *Team → Default → Primary → member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.member[].profile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile: prismic.ImageField<never>;

  /**
   * name field in *Team → Default → Primary → member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.member[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * category field in *Team → Default → Primary → member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.member[].category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * content field in *Team → Default → Primary → member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.member[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * title field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * content field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * member field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.member[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  member: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryMemberItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → testimonial*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialItem {
  /**
   * content field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * name field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * job_type field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].job_type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_type: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * testimonial field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Item in *TourTypes → Default → Primary → category*
 */
export interface TourTypesSliceDefaultPrimaryCategoryItem {
  /**
   * title field in *TourTypes → Default → Primary → category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_types.default.primary.category[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * categoryName field in *TourTypes → Default → Primary → category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_types.default.primary.category[].categoryname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  categoryname: prismic.RichTextField;

  /**
   * content field in *TourTypes → Default → Primary → category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_types.default.primary.category[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * link field in *TourTypes → Default → Primary → category*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_types.default.primary.category[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *TourTypes → Default → Primary*
 */
export interface TourTypesSliceDefaultPrimary {
  /**
   * category field in *TourTypes → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_types.default.primary.category[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  category: prismic.GroupField<
    Simplify<TourTypesSliceDefaultPrimaryCategoryItem>
  >;
}

/**
 * Default variation for TourTypes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TourTypesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TourTypesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TourTypes*
 */
type TourTypesSliceVariation = TourTypesSliceDefault;

/**
 * TourTypes Shared Slice
 *
 * - **API ID**: `tour_types`
 * - **Description**: TourTypes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TourTypesSlice = prismic.SharedSlice<
  "tour_types",
  TourTypesSliceVariation
>;

/**
 * Primary content in *Trip → Default → Primary*
 */
export interface TripSliceDefaultPrimary {
  /**
   * title field in *Trip → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Trip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * duration field in *Trip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.default.primary.duration
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  duration: prismic.KeyTextField;

  /**
   * numberOfPeople field in *Trip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.default.primary.numberofpeople
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  numberofpeople: prismic.KeyTextField;

  /**
   * price field in *Trip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.default.primary.price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * image field in *Trip → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * activity field in *Trip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.default.primary.activity
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  activity: prismic.KeyTextField;
}

/**
 * Default variation for Trip Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TripSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Trip*
 */
type TripSliceVariation = TripSliceDefault;

/**
 * Trip Shared Slice
 *
 * - **API ID**: `trip`
 * - **Description**: Trip
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripSlice = prismic.SharedSlice<"trip", TripSliceVariation>;

/**
 * Item in *Trips → Default → Primary → trip*
 */
export interface TripsSliceDefaultPrimaryTripItem {
  /**
   * image field in *Trips → Default → Primary → trip*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trips.default.primary.trip[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * category field in *Trips → Default → Primary → trip*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trips.default.primary.trip[].category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * title field in *Trips → Default → Primary → trip*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trips.default.primary.trip[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * price field in *Trips → Default → Primary → trip*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trips.default.primary.trip[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * link field in *Trips → Default → Primary → trip*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: trips.default.primary.trip[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Trips → Default → Primary*
 */
export interface TripsSliceDefaultPrimary {
  /**
   * trip field in *Trips → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: trips.default.primary.trip[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  trip: prismic.GroupField<Simplify<TripsSliceDefaultPrimaryTripItem>>;
}

/**
 * Default variation for Trips Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TripsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Trips*
 */
type TripsSliceVariation = TripsSliceDefault;

/**
 * Trips Shared Slice
 *
 * - **API ID**: `trips`
 * - **Description**: Trips
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripsSlice = prismic.SharedSlice<"trips", TripsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LogoDocument,
      LogoDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentPreviewSlice,
      ContentPreviewSliceDefaultPrimaryTourItem,
      ContentPreviewSliceDefaultPrimary,
      ContentPreviewSliceVariation,
      ContentPreviewSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceWithoutButtonPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithoutButton,
      StatisticsSlice,
      StatisticsSliceDefaultPrimaryStatsItem,
      StatisticsSliceDefaultPrimary,
      StatisticsSliceVariation,
      StatisticsSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryMemberItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TourTypesSlice,
      TourTypesSliceDefaultPrimaryCategoryItem,
      TourTypesSliceDefaultPrimary,
      TourTypesSliceVariation,
      TourTypesSliceDefault,
      TripSlice,
      TripSliceDefaultPrimary,
      TripSliceVariation,
      TripSliceDefault,
      TripsSlice,
      TripsSliceDefaultPrimaryTripItem,
      TripsSliceDefaultPrimary,
      TripsSliceVariation,
      TripsSliceDefault,
    };
  }
}
