// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_preview: dynamic(() => import("./ContentPreview")),
  hero: dynamic(() => import("./Hero")),
  statistics: dynamic(() => import("./Statistics")),
  team: dynamic(() => import("./Team")),
  testimonials: dynamic(() => import("./Testimonials")),
  tour_types: dynamic(() => import("./TourTypes")),
  trip: dynamic(() => import("./Trip")),
  trips: dynamic(() => import("./Trips")),
};
